GCC error! :D
do.nim(119, 6) Hint: 'do.move(self: ref Cart)[declared in do.nim(119, 5)]' is declared but not used [XDeclaredButNotUsed]
CC: do
Error: execution of an external compiler program 'gcc -c  -w  -I/home/ed/.choosenim/toolchains/nim-0.19.0/lib -o /home/ed/.cache/nim/do_d/do.c.o /home/ed/.cache/nim/do_d/do.c' failed with exit code: 1

/home/ed/.cache/nim/do_d/do.c: In function ‘tick_hg9bBRiRbewDje4cWQ4LTlw_2’:
/home/ed/.cache/nim/do_d/do.c:1071:9: error: incompatible types when assigning to type ‘tyObject_Cart_hBCv1gSvzQob84kHAIWq9bw’ {aka ‘struct tyObject_Cart_hBCv1gSvzQob84kHAIWq9bw’} from type ‘tyObject_Cart_hBCv1gSvzQob84kHAIWq9bw *’ {aka ‘struct tyObject_Cart_hBCv1gSvzQob84kHAIWq9bw *’}
     T5_ = cart;